#include "cppseed/template_catalog.hpp"

#include <array>

namespace cppseed {
namespace {

constexpr std::array<TemplateSpec, 9> templates{{
    {"CMakeLists.txt", R"cppseed(cmake_minimum_required(VERSION 3.20)
project({{PROJECT_NAME}} LANGUAGES CXX)

set(CMAKE_CXX_EXTENSIONS OFF)

add_library({{NORMALIZED_NAME}}_lib STATIC src/hello.cpp)
target_include_directories(
  {{NORMALIZED_NAME}}_lib
  PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
)
target_compile_features({{NORMALIZED_NAME}}_lib PUBLIC {{CMAKE_FEATURE}})

add_executable({{PROJECT_NAME}} src/main.cpp)
target_link_libraries({{PROJECT_NAME}} PRIVATE {{NORMALIZED_NAME}}_lib)
target_compile_features({{PROJECT_NAME}} PRIVATE {{CMAKE_FEATURE}})

include(CTest)
if(BUILD_TESTING AND CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  add_subdirectory(tests)
endif()
)cppseed"},
    {"README.md", R"cppseed(# {{PROJECT_NAME}}

A small C++{{CPP_STANDARD}} project generated by cppseed.

## Build

```console
cmake -S . -B build
cmake --build build
```

## Test

```console
ctest --test-dir build --output-on-failure
```

## Run

The executable location depends on the selected CMake generator. For a typical
single-configuration generator:

```console
./build/{{PROJECT_NAME}}
```

The generated code is yours to use, modify, and distribute. Its use is not
restricted by cppseed's license.
)cppseed"},
    {".clang-format", R"cppseed(BasedOnStyle: Google
Language: Cpp
Standard: c++{{CPP_STANDARD}}
)cppseed"},
    {".gitignore", R"cppseed(build/
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
CTestTestfile.cmake
Makefile
*.o
*.obj
*.a
*.lib
*.exe
)cppseed"},
    {"include/{{NORMALIZED_NAME}}/hello.hpp",
     R"cppseed(#pragma once

#include <string>

namespace {{NORMALIZED_NAME}} {

[[nodiscard]] std::string hello();

}  // namespace {{NORMALIZED_NAME}}
)cppseed"},
    {"src/hello.cpp", R"cppseed(#include "{{NORMALIZED_NAME}}/hello.hpp"

namespace {{NORMALIZED_NAME}} {

std::string hello() { return "Hello from {{PROJECT_NAME}}!"; }

}  // namespace {{NORMALIZED_NAME}}
)cppseed"},
    {"src/main.cpp", R"cppseed(#include <iostream>

#include "{{NORMALIZED_NAME}}/hello.hpp"

int main() {
    std::cout << {{NORMALIZED_NAME}}::hello() << '\n';
    return 0;
}
)cppseed"},
    {"tests/CMakeLists.txt",
     R"cppseed(add_executable({{NORMALIZED_NAME}}_test hello_test.cpp)
target_link_libraries({{NORMALIZED_NAME}}_test PRIVATE {{NORMALIZED_NAME}}_lib)
target_compile_features({{NORMALIZED_NAME}}_test PRIVATE {{CMAKE_FEATURE}})

add_test(NAME {{NORMALIZED_NAME}}.hello COMMAND {{NORMALIZED_NAME}}_test)
)cppseed"},
    {"tests/hello_test.cpp",
     R"cppseed(#include <iostream>

#include "{{NORMALIZED_NAME}}/hello.hpp"

int main() {
    const auto actual = {{NORMALIZED_NAME}}::hello();
    const auto expected = "Hello from {{PROJECT_NAME}}!";
    if (actual != expected) {
        std::cerr << "expected: " << expected << '\n'
                  << "actual: " << actual << '\n';
        return 1;
    }
    return 0;
}
)cppseed"},
}};

}  // namespace

std::span<const TemplateSpec> project_templates() noexcept { return templates; }

}  // namespace cppseed
